apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: NodePort
  selector:
    app: java
  ports:
    - port: 80   # Port exposed by the service
      targetPort: 8081   # Port on the container
      nodePort: 30080
